### ISSUE TITLE
PolyA-miner gene model

### ISSUE THREAD

**Issue by borshago** [LiuzLab/PolyA-miner#1]
Hi!

I was wondering how PolyA-miner treats partly overlapping transcript isoforms in the reference gene bed file. Does it collapse them into a single gene or does it apply the pipeline to each transcript?

Best regards,
Daniel

**Comment by hari-yalamanchili** [comment]
Hi Daniel, 

Thank you for your interest in PolyA-miner. In the current release each gene is abstracted as the number of polyadenylation sites of all the constituent (partly overlapping) transcripts. However, in the next update polyadenylation sites will be grouped by the terminal exon.

Best,
Hari
