### ISSUE TITLE
Strange output file formats

### ISSUE THREAD

**Issue by borshago** [LiuzLab/PolyA-miner#4]
Hi,

The output files generated by polyaminer with my own data are strangely formatted.

PolyAminer.Out.PolyA-miner.Results.txt:

> Gene | No. APAsites | APAsites | APAsitesScores | MaxAPASwitch | CP | TP | CD | TD | FC | Stability | Pvalue | Adj-Pvalue
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> Downstream | 4 | chr13_46678014_46678066_.; chr3_88542026_88542078_.; chr3_104794409_104794461_.; chr7_141090460_141090512_. | 0.016504464928578155; 0.03957320724220159; 0.0011947286668250179; 0.021874013646798363 | 2 |   |   |   |   |   | 0.201298701298701 | 0.036835692666722 | 0.055253539000083
> Exon | 5 | chr1_161038488_161038540_.; chr15_58341470_58341522_.; chr19_6906696_6906755_.; chr8_70312940_70312992_.; chr8_70762772_70762824_. | 0.015272944983635434; 0.008678576479204336; 0.05158724724187355; 0.005941311120579051; 0.021694414658454647 | 3 |   |   |   |   |   | 0.168384879725086 | 0.011918978586499 | 0.035756935759498
> Distal | 2 | chr4_45804554_45804606_.; chr9_7699535_7699587_. | 0.0443285762993485; 0.04432857629934839 | 1 |   |   |   |   |   | 0.288025889967637 | 0.020249249289293 | 0.040498498578586
> 5p_UTR | 5 | chr1_133321891_133321943_.; chr19_4153983_4154035_.; chr19_6067989_6068041_.; chr5_115098202_115098254_.; chr7_3665789_3665841_. | 0.006363985859686783; 0.0073050027652331595; 0.007423005763542351; 0.01123157519910535; 0.004749586341109446 | 4 |   |   |   |   |   | 0.167259786476868 | 0.000323724879084 | 0.001942349274502
> 3p_UTR | 2 | chr1_171518122_171518174_.; chr10_117287796_117287848_. | 0.012640696858951639; 0.012640696858951639 | 1 |   |   |   |   |   | 0.297142857142857 | 0.630376107745769 | 0.630376107745769
> Promoter | 5 | chr8_21135546_21135598_.; chr8_21455429_21455481_.; chr8_21593374_21593426_.; chr8_21656683_21656735_.; chr8_21735419_21735471_. | 0.005218299809502419; 0.000698790381289921; 0.0009663547059181044; 0.010249970395948133; 0.01713341529265866 | 5 |   |   |   |   |   | 0.223880597014925 | 0.055269230655682 | 0.066323076786818
> 

PolyAminer.Out_APA.CountMatrix.txt:

> feature_id | gene_id | control1.fastq | control2.fastq | test1.fastq | test2.fastq
> -- | -- | -- | -- | -- | --
> chr13_46678014_46678066_. | Downstream | 447 | 849 | 399 | 934
> chr3_88542026_88542078_. | Downstream | 298 | 433 | 315 | 650
> chr3_104794409_104794461_. | Downstream | 497 | 628 | 443 | 767
> chr7_141090460_141090512_. | Downstream | 262 | 447 | 254 | 383
> chr1_161038488_161038540_. | Exon | 593 | 1039 | 547 | 1698
> chr15_58341470_58341522_. | Exon | 1448 | 1749 | 1373 | 2575
> chr19_6906696_6906755_. | Exon | 607 | 1129 | 502 | 929
> chr8_70312940_70312992_. | Exon | 615 | 745 | 617 | 1060
> chr8_70762772_70762824_. | Exon | 442 | 969 | 586 | 1311
> chr4_45804554_45804606_. | Distal | 2089 | 3549 | 1939 | 4453
> chr9_7699535_7699587_. | Distal | 7476 | 20988 | 7954 | 12962
> chr1_133321891_133321943_. | 5p_UTR | 81 | 191 | 85 | 195
> chr19_4153983_4154035_. | 5p_UTR | 550 | 619 | 462 | 898
> chr19_6067989_6068041_. | 5p_UTR | 182 | 233 | 168 | 259
> chr5_115098202_115098254_. | 5p_UTR | 149 | 181 | 166 | 222
> chr7_3665789_3665841_. | 5p_UTR | 331 | 526 | 272 | 711
> chr1_171518122_171518174_. | 3p_UTR | 80472 | 319585 | 101895 | 169823
> chr10_117287796_117287848_. | 3p_UTR | 160892 | 671613 | 170918 | 382246
> chr8_21135546_21135598_. | Promoter | 251276 | 664095 | 263737 | 417462
> chr8_21455429_21455481_. | Promoter | 153569 | 537973 | 211264 | 266155
> chr8_21593374_21593426_. | Promoter | 153778 | 537543 | 211245 | 265108
> chr8_21656683_21656735_. | Promoter | 286782 | 938642 | 308147 | 550063
> chr8_21735419_21735471_. | Promoter | 389799 | 1258801 | 493017 | 765629

I'm using the Gencode mouse v23 reference gene annotation in bed format. The first few lines look like this:

> chr1 | 3073252 | 3074322 | ENSMUSG00000102693.1 | 2 | +
> -- | -- | -- | -- | -- | --
> chr1 | 3102015 | 3102125 | ENSMUSG00000064842.1 | 3 | +
> chr1 | 3205900 | 3671498 | ENSMUSG00000051951.5 | 2 | -
> chr1 | 3252756 | 3253236 | ENSMUSG00000102851.1 | 1 | +
> chr1 | 3365730 | 3368549 | ENSMUSG00000103377.1 | 2 | -
> chr1 | 3375555 | 3377788 | ENSMUSG00000104017.1 | 2 | -
> chr1 | 3464976 | 3467285 | ENSMUSG00000103025.1 | 2 | -
> chr1 | 3466586 | 3513553 | ENSMUSG00000089699.1 | 2 | +
> chr1 | 3512450 | 3514507 | ENSMUSG00000103201.1 | 2 | -
> chr1 | 3531794 | 3532720 | ENSMUSG00000103147.1 | 1 | +
> 

As the polya site database, I'm using the Gencode mouse v23 polya site annotations. I formatted the file based on the order of columns set on line 14 of ExtAnnotatedAPA.py. The first few lines look like this:

> chr1 | 3214480 | 3214482 | ENSMUSG00000051951.5 | 3p_UTR | -
> -- | -- | -- | -- | -- | --
> chr1 | 3513551 | 3513553 | ENSMUSG00000051951.5 | Exon | +
> chr1 | 4344145 | 4344147 | ENSMUSG00000025900.12 | 3p_UTR | -
> chr1 | 4344148 | 4344150 | ENSMUSG00000025900.12 | 3p_UTR | -
> chr1 | 4344153 | 4344155 | ENSMUSG00000025900.12 | 3p_UTR | -
> chr1 | 4490930 | 4490932 | ENSMUSG00000025902.13 | 3p_UTR | -
> chr1 | 4773205 | 4773207 | ENSMUSG00000033845.13 | 3p_UTR | -
> chr1 | 4776376 | 4776378 | ENSMUSG00000033845.13 | 3p_UTR | -
> chr1 | 4776377 | 4776379 | ENSMUSG00000033845.13 | 3p_UTR | -
> chr1 | 4846733 | 4846735 | ENSMUSG00000025903.14 | 3p_UTR | +
> 

Any ideas on what goes wrong here?

Best,
Daniel

**Comment by ericjason11111** [comment]
I have the same problem!

**Comment by hari-yalamanchili** [comment]
Behavior of the bedtools merge function from V2.26 to V 2.29/2.30 is updated and this is causing the hiccups. Fixed in the recent update.
