### ISSUE TITLE
suitability for pac-seq libraries primed with unanchored oligo-dt?

### ISSUE THREAD

**Issue by kriemo** [LiuzLab/PolyA-miner#7]
I am interested in applying PolyA-miner to analyze Poly(A)-ClickSeq libraries. However it is unclear from the documentation if this tool will be suitable. The libraries that I am analyzing were primed with an unanchored oligodT primer (e.g. `T(21)` not `T(21)VN`)  which enables sequencing of an additional portion of the poly(A) tail not templated by the RT primer. Does polyA-miner use the length of the polyA stretch in each read for filtering or calling de novo poly(A) sites, similar to the [DPAC-seq](https://sourceforge.net/projects/dpac-seq/) tool? Also, is the `-umi` option described in your recent [methods chapter](https://doi.org/10.1016/bs.mie.2021.04.001) available? Thanks in advance.

**Comment by hari-yalamanchili** [comment]
Hi Kriemo,
PolyA-miner do not use the length of the polyA stretch. It maps all possible de novo poly(A) sites and scan for genomic polyAs to filter the misprimed sites. UMI, beta-binomial model and bam options are available in v1.1. You can start with pre-aligned bam files.
Thanks!
